title: STCData
description: System for collecting ML data from mobile devices
theme: just-the-docs
plugins:
  - jekyll-spaceship
jekyll-spaceship:
  mermaid-processor:
    mode: default  # mode value 'pre-fetch' for fetching image at building stage
    css:
      class: mermaid
    syntax:
      code: 'mermaid'
      custom: ['@startmermaid', '@endmermaid']
    config:
      theme: default
    src: https://mermaid.ink/svg/
