title: STCData
description: System for collecting ML data from mobile devices
theme: just-the-docs
plugins:
  - jekyll-spaceship
jekyll-spaceship:
  mermaid-processor:
    mode: default  # mode value 'pre-fetch' for fetching image at building stage
    css:
      class: mermaid
    syntax:
      code: 'mermaid'
      custom: ['@startmermaid', '@endmermaid']
    config:
      theme: default
    src: https://mermaid.ink/svg/


nav_external_links:
  - title: STCiOSXDataCollector
    url: https://github.com/STCData/STCiOSXDataCollector
    hide_icon: false 
  - title: STCDroneDataCollector
    url: https://github.com/STCData/STCDroneDataCollector
    hide_icon: false 
  - title: STCDataServer
    url: https://github.com/STCData/STCDataServer
    hide_icon: false   
  - title: STCX11DataCollector
    url: https://github.com/STCData/STCX11DataCollector
    hide_icon: false 
